name: python app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo "current directory: "
        pwd
        ls -l
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install youtube_dl and mutagen
      run: |
        python --version
        python -m pip install --upgrade pip
        pip --version
        pip install youtube_dl
        find . -name "youtube_dl*"
        pip install mutagen
#    - name: Test the app
#      run: |
#        ./youtube-audio-extract.py --workpath . https://www.youtube.com/watch?v=ZTdOMV-yTRg Marillion Lavender
